################################################
#R Basics - code file
#Associate Professor Ole Maneesoonthorn
################################################

#Installing a package - you only need to do this once
install.packages("fpp3")

#Telling R that you wish to use this package for the current session.
#You need to do this every time a new session is started.
library("fpp3")

#Case sensitivity
abc="abc"
ABC="ABC"

abc
ABC

##R Syntax
#Examples of expressions
4*5
5*(6+7)

#Examples of assignment - "=" and "<-" do the same job
x=4
y<-5

#An assignment does not automatically print...
#To look at what x and y contain:
x
y

#Examples of assignment of expression
a<-4*5
a
b<-5*(6+7)
b
c=a+b
c

##Vector, matrix and array objects
# A 3x1 vector of zeros
v=c(0,0,0)
# Checking the length of v
length(v)

# A 3x2 matrix, filled with zero
m=matrix(0,nrow=3,ncol=2)
# Checking the dimension of m
dim(m)

# An array of size 3x2x2, filled with zero
a=array(0,c(3,2,2))
#checking the dimension of a
dim(a)

##Data Frames
#An example of creation of data frame. 
#Name is a collection of characters
name=c("Abby","Bob","Chris")
#Height is numeric
height=c(165,188,179)
#A dataframe can contain data of different types
data=data.frame(name,height)
#Naming the variables makes it easier to access later
names(data)=c("name","height")
data

#You can call the variable from the dataframe using the "$" sign
data$name
data$height

##List Objects
#First let's create some items
a=matrix(0,nrow=5,ncol=10)
b=300

#You can collect together a and b in a list
ab_list=list(A=a,B=b)

#To call the components of the list, use "$" sign
ab_list$A
ab_list$B

##Model fit objects
#Let's take an example data from "fpp" package
library(fpp)
data(fuel)

#Fit a model of Carbon=b0+b1*City+error
fit=lm(Carbon~City,data=fuel)

#Taking a look at the coefficients
fit$coefficients

#View a summary of the model fit
summary(fit)

##Setting work directory to the location specified in the quotation marks
# setwd("C:\Users\Ole\Document\Predictive")

##Importing and Exporting Data
#Ensure that "salary.csv" is saved in your working directory
#The most convenient data format is the .csv format
salary=read.csv(file="RComp_code&data/salary.csv",header=TRUE)

#Let's look at the first few lines
head(salary)

##Writing your own functions
#A function to compute relative change from x1 to x2, where x1 is the base value
relative_change<-function(x1,x2){
  dec=(x2-x1)/x1
  perc=dec*100
  return(list(percentage=perc,decimal=dec))
}

#Let's call the function
result=relative_change(100,101)
result$percentage
result$decimal

##IF/ELSE statements
#Compute the relative change if x1<x2, do nothing otherwise.
x1=100
x2=101

if(x1<x2){
  rc1=relative_change(x1,x2)
}
rc1

#Compute the relative change if x1<x2, return zero results otherwise.
#Redefine x2 to test this.
x2=90
if(x1<x2){
  rc2=relative_change(x1,x2)
} else {
  rc2=list(percentage=0, decimal=0)
}
rc2

##For loop for repeated calculations
#This is a loop to compute the relative change multiple times, 
#depending on the size of x1 and x2 (they must be of the same size)

#seq() is a command to generage a sequence
x1=seq(from=100,to=120,by=1) 
x2=seq(from=101,to=121,by=1)

#first find out the length of x1
n=length(x1)
#create storate vector for percentage and decimal changes
perc=matrix(0,n,1)
dec=matrix(0,n,1)
for(i in 1:n){
  #store the list in a tmp object
  tmp=relative_change(x1[i],x2[i])
  #allocate percentage and decimal changes appropriately
  perc[i]=tmp$percentage
  dec[i]=tmp$decimal
}
perc
dec

sample_matrix=matrix(n,1)
sample_matrix

#Note: some of you may recognize that R is a matrix language. 
#So this for loop will produce equivalent results to relative_change(x1,x2)!

##While loop for repeated calculations under some conditions
#Let's use x1 and x2 generated by the above for loop example. 
#Construct a while loop to compute the relative change while the change>0.9%.
#Record the relative changes that are >=0.9%.

#set a tmp value for the condition
chg=1
#set an index for access to x1 and x2
i=1
while(chg>0.9){
  tmp=relative_change(x1[i],x2[i])
  if(i==1){
    #if this is the first computation, assign a value
    perc2=tmp$percentage
    dec2=tmp$decimal
  }else if(tmp$percentage>0.9){
    #otherwise, add the new results to existing ones.
    #"rbind" is used to add additional rows.
    #The second layer of "if" is there to trap out 
    #the final result that may be less than 0.9%.
    perc2=rbind(perc2,tmp$percentage)
    dec2=rbind(dec2,tmp$decimal)
  }
  #reset the condition
  chg=tmp$percentage
  #increment the index to move on to the next element
  i=i+1
}

perc2
dec2